import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "UTM Builder",
  slug: "utm-builder",
  category: "creator",
  shortDescription: "Build UTM tracking links for your marketing campaigns.",
  longDescription: "Create properly formatted UTM-tagged URLs to track the effectiveness of your marketing campaigns. Add source, medium, campaign, content, and term parameters. Keep your analytics clean and track traffic sources accurately.",
  metaTitle: "UTM Link Builder - Create Tracking URLs Free | FreeKit",
  metaDescription: "Build UTM tracking links for your marketing campaigns for free. Track traffic sources, campaigns, and content across analytics platforms.",
  keywords: ["utm builder", "utm link", "tracking url", "campaign tracking"],
  tags: ["creator", "marketing", "analytics", "url"],
  icon: "Link",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 3,
  toolOrder: 3,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["url-encoder", "qr-code-generator", "og-image-generator"],
  searchPriority: 85,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["utm link generator", "campaign url builder", "google analytics url builder", "tracking link creator"],
  version: "1.0.0",
}
