import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Image Watermark Tool",
  slug: "watermark-image",
  category: "image",
  shortDescription:
    "Add text watermarks to images with customizable position, font size, color, opacity, and rotation.",
  longDescription:
    "Protect your images with customizable text watermarks. Upload a PNG, JPG, or WebP image, enter your watermark text, and fine-tune the appearance with controls for font size, color, opacity, and rotation angle. Choose from four positioning modes: center, tiled (repeated across the image), or placed in the four corners. See a live canvas preview that updates in real time as you adjust settings. Download the watermarked image in the same format as the original.",
  metaTitle:
    "Image Watermark Tool | Add Text Watermark to Images Online Free | FreeKit",
  metaDescription:
    "Add text watermarks to images online for free. Customizable position (center, tiled, corners), font size, color, opacity, and rotation. Live preview, no upload needed.",
  keywords: [
    "watermark image",
    "add watermark",
    "text watermark",
    "image watermark tool",
    "copyright watermark",
    "watermark photos",
    "protect images",
    "batch watermark",
    "watermark online",
    "photo watermark generator",
  ],
  tags: [
    "image",
    "watermark",
    "text",
    "copyright",
    "protection",
    "overlay",
    "png",
    "jpg",
    "webp",
  ],
  icon: "Stamp",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 7,
  toolOrder: 7,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-24",
  relatedTools: [
    "image-compressor",
    "image-resizer",
    "png-to-jpg",
    "jpg-to-png",
    "image-to-webp",
  ],
  searchPriority: 83,
  readingTime: 3,
  clientSide: true,
  searchAliases: [
    "add text to image",
    "copyright image tool",
    "image protection tool",
    "put watermark on photo",
    "watermark generator",
    "create watermark",
  ],
  version: "1.0.0",
}
