import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Text to Markdown",
  slug: "text-to-markdown",
  category: "document",
  shortDescription: "Convert plain text to structured Markdown format.",
  longDescription: "Transform unstructured plain text into clean, well-formatted Markdown with smart detection of headings, lists, links, bold and italic text. Automatically recognizes patterns like ALL CAPS headings, numbered lists, bullet points, and URLs to produce properly structured Markdown output.",
  metaTitle: "Text to Markdown Converter - Convert Plain Text to MD Free | FreeKit",
  metaDescription: "Convert plain text to Markdown format for free. Auto-detect headings, lists, links, and formatting. Smart conversion with instant results in your browser.",
  keywords: ["text to markdown", "plain text to markdown", "convert text to md", "text markdown converter"],
  tags: ["document", "text", "markdown", "converter"],
  icon: "FileCode",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 2,
  toolOrder: 2,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["pdf-to-markdown", "markdown-to-html", "html-to-markdown", "markdown-editor-preview"],
  searchPriority: 84,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["convert plain text to markdown", "text to md converter", "auto format text to markdown"],
  version: "1.0.0",
}
