import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Slug Generator",
  slug: "slug-generator",
  category: "text-cleanup",
  shortDescription: "Generate URL-friendly slugs from any text instantly.",
  longDescription: "Convert any title, heading, or text into a clean, URL-friendly slug. Supports hyphen, underscore, and dot separators, stop word removal, accent transliteration, and max length control.",
  metaTitle: "Free Slug Generator Tool — Create URL-Friendly Slugs Online | FreeKit",
  metaDescription: "Generate clean, SEO-friendly URL slugs from any text online for free. Choose separators, remove stop words, transliterate accents, and set max length. No sign-up required.",
  keywords: ["slug generator", "url slug", "permalink generator", "seo slug", "url friendly"],
  tags: ["text", "slug", "url", "seo", "generator"],
  icon: "Hash",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 3,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-02-20",
  updatedAt: "2025-06-05",
  relatedTools: ["remove-extra-spaces", "case-converter", "url-encoder"],
  searchPriority: 84,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["url slug maker", "permalink generator", "create slug", "seo url generator"],
  version: "1.0.0",
}
