import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "PDF to Markdown",
  slug: "pdf-to-markdown",
  category: "document",
  shortDescription: "Convert PDF documents to clean Markdown format instantly.",
  longDescription: "Extract content from PDF files and convert it to clean, well-structured Markdown. Preserves headings, paragraphs, lists, tables, and basic formatting. Perfect for converting PDFs into editable content for blogs, documentation, and note-taking apps.",
  metaTitle: "PDF to Markdown Converter - Convert PDF to MD Free | FreeKit",
  metaDescription: "Convert PDF files to Markdown format for free. Extract text with headings, paragraphs, and lists preserved. Download as .md file instantly in your browser.",
  keywords: ["pdf to markdown", "pdf to md", "convert pdf to markdown", "extract text pdf markdown"],
  tags: ["document", "pdf", "markdown", "converter"],
  icon: "FileText",
  featured: true,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 1,
  featuredOrder: 9,
  difficulty: "Intermediate",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["pdf-to-text", "text-to-markdown", "markdown-to-html", "word-counter"],
  searchPriority: 90,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["extract text from pdf to markdown", "pdf to md", "convert pdf document to markdown"],
  version: "1.0.0",
}
