import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Text to Table Converter",
  slug: "text-to-table-converter",
  category: "text-cleanup",
  shortDescription: "Convert delimited text into HTML and Markdown tables instantly.",
  longDescription: "Transform tab, comma, semicolon, or pipe-separated text into properly formatted HTML and Markdown tables. Supports first-row-as-header, whitespace trimming, and multiple delimiter types. Copy the generated table code with one click.",
  metaTitle: "Free Text to Table Converter — Delimited Text to HTML/Markdown Table | FreeKit",
  metaDescription: "Convert comma, tab, semicolon, or pipe-separated text into HTML and Markdown tables online for free. First row as header, trim whitespace, and copy table code instantly.",
  keywords: ["text to table", "CSV to table", "convert text to table", "markdown table generator", "HTML table generator", "delimited to table"],
  tags: ["text", "cleanup", "table", "converter", "markdown", "HTML"],
  icon: "Table",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 8,
  toolOrder: 8,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-02-20",
  updatedAt: "2025-06-05",
  relatedTools: ["csv-to-json", "json-to-csv", "markdown-to-html"],
  searchPriority: 76,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["text to markdown table", "CSV to HTML table", "convert to table online", "tab separated to table"],
  version: "1.0.0",
}
