import type { ToolConfig } from "@/types"
export const toolConfig: ToolConfig = {
  title: "Base64 Encoder/Decoder",
  slug: "base64-encoder",
  category: "developer",
  shortDescription: "Encode and decode Base64 strings and files.",
  longDescription: "Encode text to Base64 or decode Base64 back to plain text. Supports UTF-8 encoding, file encoding, and batch processing. Perfect for working with APIs, data URIs, and authentication headers.",
  metaTitle: "Free Base64 Encoder/Decoder | FreeKit",
  metaDescription: "Encode and decode Base64 strings online for free. Support for text, UTF-8, and file encoding with instant results.",
  keywords: ["base64 encoder", "base64 decoder", "base64", "encode decode"],
  tags: ["base64", "encoder", "decoder", "developer"],
  icon: "Lock",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 2,
  toolOrder: 2,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-01-12",
  updatedAt: "2025-06-20",
  relatedTools: ["url-encoder", "html-encoder", "json-formatter", "uuid-generator"],
  searchPriority: 88,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["base64 encode", "base64 decode", "base64 converter"],
  version: "1.0.0",
}
