import type { ToolConfig } from "@/types"
export const toolConfig: ToolConfig = {
  title: "Noise Level Meter",
  slug: "noise-level-meter",
  category: "device",
  shortDescription: "Measure environmental noise levels in decibels using your microphone with a real-time visual gauge.",
  longDescription: "A noise level meter that uses your device's microphone and the Web Audio API AnalyserNode to measure environmental sound levels in real-time. The tool converts audio amplitude to an approximate decibel (dB) reading and displays it on a visual gauge with color-coded levels: Quiet (<40dB), Moderate (40-70dB), Loud (70-90dB), and Dangerous (>90dB). Useful for checking noise levels in your environment.",
  metaTitle: "Noise Level Meter - Measure Sound in Decibels Online | FreeKit",
  metaDescription: "Free online noise level meter. Measure environmental sound in decibels using your microphone. Real-time dB gauge with noise classification.",
  keywords: ["noise level meter", "decibel meter", "sound meter", "noise measurement", "dB meter", "sound level", "noise monitor"],
  tags: ["audio", "microphone", "measurement", "noise"],
  icon: "Activity",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 9,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-23",
  updatedAt: "2025-07-23",
  relatedTools: ["microphone-test", "speaker-test", "webcam-test"],
  searchPriority: 86,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["decibel reader", "sound level checker", "noise checker", "dB reader online"],
  version: "1.0.0",
}