import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "All-in-One Image Converter",
  slug: "all-in-one-image-converter",
  category: "image",
  shortDescription:
    "Convert images between PNG, JPG, WebP, BMP, and GIF formats with quality control and batch support.",
  longDescription:
    "A universal image converter that supports PNG, JPG/JPEG, WebP, BMP, and GIF formats for both input and output. Convert multiple images at once, adjust output quality for lossy formats like JPEG and WebP, compare file sizes before and after conversion, and download results individually or all at once. All processing happens in your browser — no uploads, no servers, completely private.",
  metaTitle:
    "Image Converter Online Free | Convert PNG JPG WebP BMP GIF | FreeKit",
  metaDescription:
    "Convert images between PNG, JPG, WebP, BMP, and GIF formats online for free. Batch convert with quality control, side-by-side preview, and instant download. No upload needed.",
  keywords: [
    "image converter",
    "image format converter",
    "png to jpg",
    "jpg to png",
    "webp converter",
    "bmp converter",
    "gif converter",
    "batch image converter",
    "convert image online",
    "image conversion tool",
  ],
  tags: [
    "image",
    "converter",
    "png",
    "jpg",
    "jpeg",
    "webp",
    "bmp",
    "gif",
    "format",
    "batch",
  ],
  icon: "Images",
  featured: true,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 4,
  toolOrder: 4,
  featuredOrder: 10,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-24",
  relatedTools: [
    "image-to-webp",
    "png-to-jpg",
    "jpg-to-png",
    "image-compressor",
    "image-resizer",
  ],
  searchPriority: 93,
  readingTime: 4,
  clientSide: true,
  searchAliases: [
    "image converter online",
    "convert image format",
    "change image format",
    "image file converter",
    "bulk image converter",
    "photo converter",
    "picture converter",
  ],
  version: "1.0.0",
}
