import type { ToolConfig } from "@/types"
export const toolConfig: ToolConfig = {
  title: "Touch Screen Test",
  slug: "touch-screen-test",
  category: "device",
  shortDescription: "Test your touchscreen by drawing on a canvas. Records touch points, detects multi-touch, and shows touch count.",
  longDescription: "A touchscreen testing tool that uses the HTML Canvas API and Touch Events to let you draw directly on screen. Every touch point is recorded and displayed as a colored dot. Lines are drawn between sequential touches. The tool detects and displays multi-touch events, making it easy to verify your touchscreen is responding accurately across the entire surface.",
  metaTitle: "Touch Screen Test - Test Your Touchscreen Online | FreeKit",
  metaDescription: "Free online touch screen test. Draw on canvas, record touch points, detect multi-touch. Verify your touchscreen works accurately.",
  keywords: ["touch screen test", "touchscreen test", "touch test", "multi-touch test", "screen touch check", "touch response test"],
  tags: ["touch", "screen", "testing", "hardware"],
  icon: "Hand",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 7,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-23",
  updatedAt: "2025-07-23",
  relatedTools: ["dead-pixel-test", "webcam-test", "microphone-test"],
  searchPriority: 84,
  readingTime: 2,
  clientSide: true,
  searchAliases: ["touchscreen checker", "touch test online", "multi-touch test", "screen draw test"],
  version: "1.0.0",
}