import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "PDF Page Extractor",
  slug: "pdf-page-extractor",
  category: "pdf",
  shortDescription: "Extract specific pages from a PDF into a new document.",
  longDescription: "Select and extract specific pages from any PDF to create a new document. Pick individual pages, ranges, or custom selections. Perfect for pulling out relevant sections from long reports or contracts.",
  metaTitle: "PDF Page Extractor - Extract Pages from PDF Free | FreeKit",
  metaDescription: "Extract specific pages from PDF documents for free. Select page ranges or individual pages to create a new PDF file instantly.",
  keywords: ["extract pdf pages", "pdf page extractor", "pull pages from pdf", "pdf page selection"],
  tags: ["pdf", "extract", "pages", "document"],
  icon: "FileOutput",
  featured: false,
  popular: false,
  published: true,
  status: "published",
  categoryOrder: 7,
  toolOrder: 7,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["pdf-splitter", "pdf-merger", "pdf-rotator", "pdf-to-text"],
  searchPriority: 82,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["extract specific pages from pdf", "pull pages from pdf", "pdf page range extractor", "remove pages from pdf"],
  version: "1.0.0",
}
