import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Sentence Counter",
  slug: "sentence-counter",
  category: "text-cleanup",
  shortDescription: "Count sentences, words, characters, and get detailed text statistics instantly.",
  longDescription: "Analyze your text with comprehensive sentence-level statistics including sentence count, word count, character count, average words per sentence, average sentence length, and identify the longest sentence. A fast, free, browser-based text analysis tool.",
  metaTitle: "Free Sentence Counter Tool — Count Sentences & Words Online | FreeKit",
  metaDescription: "Count sentences, words, characters, and paragraphs in your text online for free. Get average words per sentence, find the longest sentence, and analyze text structure instantly.",
  keywords: ["sentence counter", "count sentences", "sentence analyzer", "word count", "text statistics", "sentence length"],
  tags: ["text", "cleanup", "sentences", "counting", "statistics"],
  icon: "AlignLeft",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 5,
  toolOrder: 5,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-02-20",
  updatedAt: "2025-06-05",
  relatedTools: ["word-counter", "reading-time-calculator", "character-counter"],
  searchPriority: 80,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["count sentences online", "sentence statistics", "text analyzer", "how many sentences", "average sentence length"],
  version: "1.0.0",
}
