import type { FAQItem } from "@/types"

export const faqs: FAQItem[] = [
  {
    question: "What is a random number generator (RNG)?",
    answer:
      "A random number generator (RNG) is a tool or algorithm that produces a sequence of numbers that cannot be reasonably predicted. Our online RNG lets you set a minimum and maximum range, choose between integers or decimals, and generate single or multiple numbers at once. It runs entirely in your browser for instant, private results.",
  },
  {
    question: "What is the difference between true random and pseudo-random numbers?",
    answer:
      "True random numbers are derived from physical processes like atmospheric noise or radioactive decay, making them genuinely unpredictable. Pseudo-random numbers are generated by mathematical algorithms that start from an initial value called a seed. While pseudo-random numbers are not truly unpredictable, they are statistically indistinguishable from true random numbers for most practical purposes. Our tool uses JavaScript's crypto.getRandomValues() for cryptographic-quality randomness.",
  },
  {
    question: "Does this tool use cryptographic random generation?",
    answer:
      "Yes. Our Random Number Generator uses the Web Crypto API (crypto.getRandomValues()) provided by your browser. This is the same cryptographically secure random number generator used by your browser for HTTPS encryption, password generation, and security tokens. It provides high-quality randomness suitable for games, giveaways, sampling, and any other general purpose.",
  },
  {
    question: "Are the generated numbers fair and unbiased?",
    answer:
      "Yes. The Web Crypto API generates uniformly distributed random values, meaning every number in your specified range has an equal probability of being selected. For example, if you generate a number between 1 and 100, each integer from 1 to 100 has exactly a 1% chance of appearing. The underlying random source is designed for cryptographic use and passes rigorous statistical tests for uniformity.",
  },
  {
    question: "What does the 'Unique Only' option do?",
    answer:
      "When you enable the 'Unique Only' toggle, the generator ensures that no duplicate numbers appear in your results. For example, generating 5 unique numbers between 1 and 10 might give you [3, 7, 1, 9, 5] with no repeats. Note that if you request more unique numbers than the range allows (e.g., 200 unique numbers from a 1–100 range), the tool will show an error since it is mathematically impossible.",
  },
  {
    question: "Can I set negative numbers as the minimum value?",
    answer:
      "Absolutely. You can set any numeric range, including negative values. For example, you could set a minimum of -50 and a maximum of 50 to generate random numbers that may be positive, negative, or zero. This is useful for simulations, scoring systems, or any scenario that requires a range spanning both sides of zero.",
  },
  {
    question: "How are decimal numbers generated?",
    answer:
      "When you disable the 'Integer Only' toggle, the generator produces decimal (floating-point) numbers with up to 10 decimal places of precision. The decimal is generated by scaling the random integer result to the full range and preserving fractional precision. For example, a range of 1 to 10 might produce 7.3849261531. Decimals are automatically rounded for display but the full precision is used for sorting and copying.",
  },
  {
    question: "What is a seed value and does this tool support it?",
    answer:
      "A seed is an initial value used by pseudo-random number generators to produce a deterministic sequence of numbers. Using the same seed always produces the same sequence, which is useful for reproducibility in scientific simulations. Our tool uses the browser's cryptographic random source, which does not accept a seed and produces a different sequence every time. If you need reproducible results, you would need a deterministic PRNG library instead.",
  },
  {
    question: "What are common uses for a random number generator?",
    answer:
      "Random number generators are used in a wide variety of scenarios: picking giveaway or raffle winners, rolling virtual dice for tabletop games, selecting random samples for surveys or research, shuffling playlists or team lineups, generating test data for software development, creating random passwords and security tokens, simulating probability experiments, picking random discussion topics, and assigning random groups in classrooms or workshops.",
  },
  {
    question: "Is my data sent to a server?",
    answer:
      "No. This Random Number Generator runs entirely in your browser using client-side JavaScript and the Web Crypto API. None of the values you enter, the ranges you set, or the numbers generated are sent to any server, stored in any database, or shared with any third party. As soon as you close or refresh the page, all data is gone. Your privacy is fully protected.",
  },
]
