import type { ToolConfig } from "@/types"
export const toolConfig: ToolConfig = {
  title: "Microphone Test",
  slug: "microphone-test",
  category: "device",
  shortDescription: "Test your microphone online with real-time volume level meter, short clip recording, and playback.",
  longDescription: "A comprehensive microphone testing tool that uses the browser's getUserMedia API to access your microphone. Features a real-time volume level meter using the Web Audio API AnalyserNode, device name detection, and a short clip recording with playback functionality. Instantly verify your microphone is working, check volume levels, and hear what you sound like — all in your browser with no software installation.",
  metaTitle: "Microphone Test - Test Your Mic Online Free | FreeKit",
  metaDescription: "Free online microphone test. Check if your mic is working, see real-time volume levels, record and play back a short clip. No software needed.",
  keywords: ["microphone test", "mic test", "test microphone online", "mic check", "microphone not working", "audio input test"],
  tags: ["audio", "microphone", "testing", "hardware"],
  icon: "Mic",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 3,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-23",
  updatedAt: "2025-07-23",
  relatedTools: ["speaker-test", "noise-level-meter", "webcam-test"],
  searchPriority: 92,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["mic check", "microphone checker", "test my mic", "is my mic working"],
  version: "1.0.0",
}