import type { FAQItem } from "@/types"
export const faqs: FAQItem[] = [
  { question: "How do I test my microphone?", answer: "Click the 'Start Test' button to grant microphone permission. The tool will show your device name and a real-time volume meter. Speak into your mic to see the level bar respond. You can also record a 5-second clip and play it back." },
  { question: "Why is the volume meter not moving?", answer: "Ensure your microphone is not muted in your system settings and that you've granted browser permission. Try speaking louder or tapping the microphone gently. Also check that the correct input device is selected in your OS sound settings." },
  { question: "Can I test multiple microphones?", answer: "Yes, if you have multiple microphones connected, the browser will typically use the system default. You can change the default mic in your OS settings and restart the test to try a different device." },
  { question: "Is my audio data sent to a server?", answer: "No, all audio processing happens locally in your browser. The getUserMedia API accesses your microphone directly, and the Web Audio API processes the signal. No audio data leaves your device." },
  { question: "What does the volume level mean?", answer: "The volume level shows the relative amplitude of the audio signal from your microphone, measured as a percentage of the maximum input level. A good speaking level typically registers between 30-70%." },
  { question: "How does the recording feature work?", answer: "The tool uses the MediaRecorder API to capture a 5-second audio clip from your microphone. After recording stops, you can play it back to hear exactly what your microphone is capturing." },
  { question: "Why does the browser ask for microphone permission?", answer: "The browser requires explicit permission to access the microphone hardware for privacy and security. This is a standard web security feature. You can revoke this permission at any time in your browser settings." },
  { question: "Does this work on mobile devices?", answer: "Yes, this tool works on mobile devices that support the getUserMedia API. Most modern smartphones and tablets running updated browsers will work. The built-in microphone will be used." },
  { question: "What if my microphone is not detected?", answer: "First check that your microphone is properly connected (or not disabled in hardware). Then verify the browser has permission. Try using a different browser. If issues persist, check your OS device manager for driver issues." },
  { question: "What audio format is used for recording?", answer: "The recording uses the MediaRecorder API, which typically records in webm/opus format in Chrome and Firefox. The format is automatically chosen by your browser based on supported codecs." },
]