import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Quote / Estimate Generator",
  slug: "quote-generator",
  category: "business",
  shortDescription: "Create professional quotes and estimates for clients.",
  longDescription: "Generate professional quotes and estimates for your clients in seconds. Add your business details, client information, line items with automatic calculations, tax, discounts, terms and conditions, and notes. Preview your quote live and print or save it directly.",
  metaTitle: "Quote & Estimate Generator - Create Professional Quotes Free | FreeKit",
  metaDescription: "Create professional quotes and estimates for free with automatic calculations. Add line items, tax, discounts, terms, and print your quote instantly.",
  keywords: ["quote generator", "estimate generator", "price quote", "free quote", "business quote"],
  tags: ["business", "quote", "estimate", "pricing", "documents"],
  icon: "ClipboardList",
  featured: false,
  popular: false,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 3,
  featuredOrder: 0,
  difficulty: "Intermediate",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["invoice-generator", "resume-builder", "timesheet-calculator"],
  searchPriority: 82,
  readingTime: 6,
  clientSide: true,
  searchAliases: ["estimate creator", "price quote maker", "free estimate template", "quotation generator", "job estimate"],
  version: "1.0.0",
}
