import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Remove Duplicate Lines",
  slug: "remove-duplicate-lines",
  category: "text",
  shortDescription: "Remove duplicate lines from text while preserving order.",
  longDescription: "Quickly remove duplicate lines from any text while preserving the original order. Options for case-sensitive comparison, trimming whitespace, and removing empty lines.",
  metaTitle: "Free Remove Duplicate Lines Tool | FreeKit",
  metaDescription: "Remove duplicate lines from text online for free. Preserve order, trim whitespace, and clean up your lists instantly.",
  keywords: ["remove duplicates", "deduplicate lines", "unique lines", "remove duplicate text"],
  tags: ["text", "duplicate", "clean", "unique"],
  icon: "ListFilter",
  featured: false,
  popular: false,
  published: true,
  status: "published",
  categoryOrder: 5,
  toolOrder: 5,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-02-20",
  updatedAt: "2025-06-05",
  relatedTools: ["text-replacer", "word-counter", "case-converter", "text-sorter"],
  searchPriority: 60,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["deduplicate text", "unique line extractor", "remove repeated lines"],
  version: "1.0.0",
}
