import type { ToolConfig } from "@/types"
export const toolConfig: ToolConfig = {
  title: "Speaker Test",
  slug: "speaker-test",
  category: "device",
  shortDescription: "Test your left and right speakers with stereo audio tones, frequency sweeps, and visual waveform display.",
  longDescription: "A comprehensive speaker testing tool that plays different tones on the left and right audio channels using the Web Audio API StereoPannerNode. Test left channel, right channel, both channels, or run a full frequency sweep. The visual waveform display shows real-time audio output so you can verify your speakers are working correctly and identify any channel imbalances or dead speakers.",
  metaTitle: "Speaker Test - Test Left & Right Speakers Online | FreeKit",
  metaDescription: "Free online speaker test. Play tones on left, right, or both channels. Visual waveform display. Verify your speakers are working correctly.",
  keywords: ["speaker test", "left right speaker test", "stereo test", "audio test", "speaker check", "sound test", "channel test"],
  tags: ["audio", "speakers", "testing", "hardware"],
  icon: "Speaker",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 2,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-23",
  updatedAt: "2025-07-23",
  relatedTools: ["water-eject-tool", "microphone-test", "hearing-test"],
  searchPriority: 88,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["stereo test", "audio channel test", "sound check", "speaker check left right"],
  version: "1.0.0",
}