import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Resume Builder",
  slug: "resume-builder",
  category: "business",
  shortDescription: "Build a professional resume with live preview and print-ready output.",
  longDescription: "Create a clean, professional resume with our easy-to-use builder. Fill in your personal information, work experience, education, and skills — then preview your resume in real time and print or download it instantly. No account needed, no templates to buy.",
  metaTitle: "Resume Builder - Create Professional Resumes Free | FreeKit",
  metaDescription: "Build a professional resume for free with our online resume builder. Add experience, education, skills, and get a print-ready resume instantly.",
  keywords: ["resume builder", "cv builder", "resume maker", "free resume", "online resume"],
  tags: ["business", "resume", "cv", "career", "documents"],
  icon: "FileUser",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 1,
  featuredOrder: 0,
  difficulty: "Intermediate",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["invoice-generator", "quote-generator", "business-card-maker"],
  searchPriority: 94,
  readingTime: 6,
  clientSide: true,
  searchAliases: ["cv maker", "resume creator", "resume generator", "free cv builder", "online cv maker"],
  version: "1.0.0",
}
