import type { ToolConfig } from "@/types"
export const toolConfig: ToolConfig = {
  title: "Hearing Test",
  slug: "hearing-test",
  category: "device",
  shortDescription: "Test your hearing range by playing tones at different frequencies from 125Hz to 16kHz.",
  longDescription: "A comprehensive online hearing test that plays pure sine wave tones at various frequencies (125Hz to 16kHz) through your speakers or headphones. For each frequency, you indicate whether you can hear the tone or not. After completing all frequencies, the tool generates a visual frequency response chart showing which frequencies you can and cannot hear. This is not a medical diagnosis but can help identify potential hearing patterns.",
  metaTitle: "Hearing Test - Test Your Hearing Range Online | FreeKit",
  metaDescription: "Free online hearing test. Play tones from 125Hz to 16kHz and see your frequency response. Identify your hearing range.",
  keywords: ["hearing test", "hearing test online", "frequency test", "hearing check", "audio frequency test", "test hearing range"],
  tags: ["audio", "hearing", "health", "testing"],
  icon: "Ear",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 10,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-23",
  updatedAt: "2025-07-23",
  relatedTools: ["speaker-test", "noise-level-meter", "water-eject-tool"],
  searchPriority: 89,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["frequency hearing test", "hear test", "audio range test", "can I hear this frequency"],
  version: "1.0.0",
}