import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Reading Time Calculator",
  slug: "reading-time-calculator",
  category: "text-cleanup",
  shortDescription: "Calculate reading time, speaking time, and text statistics instantly.",
  longDescription: "Estimate how long it takes to read or speak any text. Adjustable reading speed (100-400 WPM), speaking time, word count, character count, sentence count, paragraph count, and visual progress bar.",
  metaTitle: "Free Reading Time Calculator — Estimate Read & Speak Time | FreeKit",
  metaDescription: "Calculate reading time and speaking time for any text online for free. Adjust reading speed, view word count, character count, sentences, paragraphs, and visual progress bar.",
  keywords: ["reading time calculator", "reading time estimator", "speaking time", "word count", "read time"],
  tags: ["text", "reading", "time", "calculator", "stats"],
  icon: "BookOpen",
  featured: false,
  popular: false,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 4,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-02-20",
  updatedAt: "2025-06-05",
  relatedTools: ["word-counter", "character-counter", "sentence-counter"],
  searchPriority: 80,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["estimate read time", "how long to read", "speaking time calculator", "article reading time"],
  version: "1.0.0",
}
