import type { FAQItem } from "@/types"

export const faqs: FAQItem[] = [
  { question: "What is Schema.org structured data?", answer: "Schema.org is a collaborative project that provides a collection of shared vocabularies (schemas) that webmasters can use to mark up their pages in ways recognized by major search engines. When search engines understand your content's context, they can display rich results (rich snippets) like star ratings, FAQs, breadcrumbs, and more in search results." },
  { question: "What is JSON-LD?", answer: "JSON-LD (JavaScript Object Notation for Linked Data) is the recommended format for structured data by Google. It uses a simple script tag in your HTML head: <script type='application/ld+json'>{...}</script>. It's easier to read, write, and maintain than microdata or RDFa formats." },
  { question: "What are rich snippets?", answer: "Rich snippets are enhanced search results that include extra information beyond the standard title, URL, and description. Examples include star ratings, FAQ accordions, recipe cooking times, product prices, event dates, and how-to steps. They are powered by Schema.org structured data and significantly improve click-through rates." },
  { question: "Which schema types should I use?", answer: "The most common and impactful schema types are: Article (for blog posts and news), FAQPage (for FAQ sections), Product (for e-commerce), LocalBusiness (for physical stores), Organization (for company info), BreadcrumbList (for navigation), and HowTo (for tutorials). Start with the types most relevant to your content." },
  { question: "How do I test my structured data?", answer: "Use Google's Rich Results Test (search.google.com/test/rich-results) to validate your JSON-LD. It checks for errors and shows a preview of how your rich result may appear in Google Search. Also check Google Search Console's Enhancements report for structured data issues." },
  { question: "Where do I put JSON-LD markup?", answer: "JSON-LD should be placed in the <head> section of your HTML as a <script type='application/ld+json'> tag. For Next.js, you can use the next/script component or dangerouslySetInnerHTML. Multiple JSON-LD blocks are allowed on the same page." },
  { question: "Can I have multiple schemas on one page?", answer: "Yes, you can include multiple JSON-LD blocks on a single page. For example, a product page might have a Product schema, a BreadcrumbList schema, and an Organization schema. Each should be in its own <script type='application/ld+json'> tag." },
  { question: "Does structured data improve rankings?", answer: "Structured data doesn't directly improve rankings, but it enables rich snippets which can significantly increase click-through rates (up to 20-30% higher). Google has stated that structured data helps them understand content better, which can indirectly benefit rankings." },
  { question: "What is the difference between JSON-LD, Microdata, and RDFa?", answer: "JSON-LD uses a <script> tag with JSON format and is Google's recommended format — it's the easiest to implement and maintain. Microdata uses HTML attributes (itemscope, itemtype) directly on elements and can be harder to read in source code. RDFa uses XHTML attributes and is mainly used in academic and government contexts. Our tool generates JSON-LD, which is the industry standard for modern web development." },
  { question: "Is this Schema generator free?", answer: "Yes, this tool is 100% free with no limits, no sign-up, and no hidden fees. All generation happens in your browser — no data is sent to any server." },
]
