import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Scan to PDF",
  slug: "scan-to-pdf",
  category: "pdf",
  shortDescription: "Convert scanned images and photos into searchable PDF documents.",
  longDescription: "Transform scanned documents, photos, and image captures into clean PDF files. Combine multiple scanned pages into one organized document. Ideal for digitizing paper records and creating searchable archives.",
  metaTitle: "Scan to PDF - Convert Scanned Images to PDF Free | FreeKit",
  metaDescription: "Convert scanned images and photos to PDF documents for free. Create searchable PDFs from your scanned documents and photos.",
  keywords: ["scan to pdf", "scanned document pdf", "photo to pdf scan", "document scanner"],
  tags: ["pdf", "scan", "ocr", "document"],
  icon: "Camera",
  featured: false,
  popular: false,
  published: true,
  status: "published",
  categoryOrder: 8,
  toolOrder: 8,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["jpg-to-pdf", "pdf-merger", "image-compressor", "image-to-text-ocr"],
  searchPriority: 78,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["scanned document to pdf", "photo scan to pdf", "document scanning online", "create pdf from scan"],
  version: "1.0.0",
}
