import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "JPG to PDF",
  slug: "jpg-to-pdf",
  category: "pdf",
  shortDescription: "Convert JPG and JPEG images to PDF documents in seconds.",
  longDescription: "Transform your JPG and JPEG images into professional PDF documents. Upload single or multiple images and convert them instantly. Great for creating photo albums, scanned document archives, or image-based reports.",
  metaTitle: "JPG to PDF Converter - Convert Images to PDF Free | FreeKit",
  metaDescription: "Convert JPG and JPEG images to PDF documents for free. Upload multiple images and create a single PDF file instantly.",
  keywords: ["jpg to pdf", "jpeg to pdf", "image to pdf", "convert jpg"],
  tags: ["pdf", "image", "converter", "jpg"],
  icon: "ImagePlus",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 3,
  toolOrder: 3,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["pdf-to-jpg", "pdf-merger", "image-compressor", "image-to-webp"],
  searchPriority: 92,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["jpeg to pdf converter", "image to pdf online", "convert photos to pdf", "jpg pdf maker"],
  version: "1.0.0",
}
