import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "PDF Splitter",
  slug: "pdf-splitter",
  category: "pdf",
  shortDescription: "Split a PDF file into separate pages or smaller documents.",
  longDescription: "Split any PDF into individual pages or custom ranges. Extract specific sections from large documents effortlessly. Ideal for separating chapters, extracting receipts, or breaking down large reports.",
  metaTitle: "PDF Splitter - Split PDF Files Online Free | FreeKit",
  metaDescription: "Split PDF files into individual pages or custom ranges for free. Extract specific sections without losing quality. Fast and secure.",
  keywords: ["split pdf", "pdf splitter", "separate pdf pages", "extract pdf pages"],
  tags: ["pdf", "split", "extract", "document"],
  icon: "Scissors",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 2,
  toolOrder: 2,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["pdf-merger", "pdf-page-extractor", "pdf-rotator", "pdf-to-text"],
  searchPriority: 93,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["separate pdf pages", "extract pages from pdf", "divide pdf", "pdf page separator"],
  version: "1.0.0",
}
