import type { ToolConfig } from "@/types"
export const toolConfig: ToolConfig = {
  title: "Mirror Online",
  slug: "mirror-online",
  category: "device",
  shortDescription: "Turn your webcam into a fullscreen mirror with a clean, distraction-free view.",
  longDescription: "A simple and elegant online mirror that uses your device's webcam with a CSS mirror transform to create a natural mirror-like experience. Features a fullscreen mode for a true mirror feel, minimal UI for a distraction-free view, and instant activation. Perfect for quick self-checks, makeup checks, or any situation where you need a mirror but don't have one.",
  metaTitle: "Mirror Online - Free Webcam Mirror | FreeKit",
  metaDescription: "Free online mirror using your webcam. Fullscreen mirror view with no distractions. Quick self-check anytime, anywhere.",
  keywords: ["mirror online", "webcam mirror", "online mirror", "screen mirror", "camera mirror", "digital mirror"],
  tags: ["camera", "mirror", "utility"],
  icon: "FlipHorizontal2",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 5,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-23",
  updatedAt: "2025-07-23",
  relatedTools: ["webcam-test", "touch-screen-test", "speaker-test"],
  searchPriority: 85,
  readingTime: 2,
  clientSide: true,
  searchAliases: ["webcam mirror", "camera mirror", "selfie mirror", "online looking glass"],
  version: "1.0.0",
}