import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Photo Collage Maker",
  slug: "photo-collage-maker",
  category: "creator",
  shortDescription: "Create beautiful photo collages with customizable layouts.",
  longDescription: "Design stunning photo collages with various grid layouts, borders, and spacing options. Combine multiple photos into one beautiful composition. Ideal for social media posts, invitations, and visual storytelling.",
  metaTitle: "Photo Collage Maker - Create Collages Online Free | FreeKit",
  metaDescription: "Create photo collages online for free. Choose from grid layouts, add borders, and combine multiple photos into beautiful compositions.",
  keywords: ["photo collage", "collage maker", "image collage", "picture collage"],
  tags: ["creator", "collage", "photo", "design"],
  icon: "LayoutGrid",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 8,
  toolOrder: 8,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["meme-generator", "image-cropper", "background-remover", "image-resizer"],
  searchPriority: 84,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["collage creator online", "photo grid maker", "image collage generator", "picture grid"],
  version: "1.0.0",
}