import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "PDF to Text",
  slug: "pdf-to-text",
  category: "pdf",
  shortDescription: "Extract text content from PDF documents instantly.",
  longDescription: "Quickly extract all text content from any PDF document. Copy, edit, or reuse text from PDF files without manual retyping. Supports both text-based and scanned PDFs with built-in OCR capabilities.",
  metaTitle: "PDF to Text Extractor - Extract Text from PDF Free | FreeKit",
  metaDescription: "Extract text from PDF documents for free. Copy and reuse text content from any PDF file instantly without retyping.",
  keywords: ["pdf to text", "extract text pdf", "pdf text extractor", "copy text from pdf"],
  tags: ["pdf", "text", "extractor", "ocr"],
  icon: "FileText",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 5,
  toolOrder: 5,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["pdf-splitter", "pdf-to-jpg", "image-to-text-ocr", "word-counter"],
  searchPriority: 90,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["extract text from pdf online", "pdf text extraction", "pdf to plain text", "copy text from pdf file"],
  version: "1.0.0",
}
