import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "PDF to JPG",
  slug: "pdf-to-jpg",
  category: "pdf",
  shortDescription: "Convert PDF pages to high-quality JPG images effortlessly.",
  longDescription: "Convert any PDF document into high-quality JPG images. Choose to convert all pages or select specific ones. Perfect for extracting images from PDFs, creating thumbnails, or sharing document content as images.",
  metaTitle: "PDF to JPG Converter - Convert PDF to Images Free | FreeKit",
  metaDescription: "Convert PDF pages to JPG images for free. Extract individual pages or entire documents as high-quality images. No quality loss.",
  keywords: ["pdf to jpg", "pdf to image", "convert pdf to jpeg", "pdf to picture"],
  tags: ["pdf", "image", "converter", "jpg"],
  icon: "ImageDown",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 4,
  toolOrder: 4,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["jpg-to-pdf", "pdf-to-text", "pdf-splitter", "image-compressor"],
  searchPriority: 91,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["pdf to jpeg converter", "extract images from pdf", "pdf to picture online", "convert pdf pages to images"],
  version: "1.0.0",
}
