import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "PDF Rotator",
  slug: "pdf-rotator",
  category: "pdf",
  shortDescription: "Rotate PDF pages to any angle with a single click.",
  longDescription: "Rotate individual pages or entire PDF documents to the correct orientation. Fix sideways or upside-down pages instantly. Useful for correcting scanned documents or reformatting pages for printing.",
  metaTitle: "PDF Rotator - Rotate PDF Pages Online Free | FreeKit",
  metaDescription: "Rotate PDF pages online for free. Fix sideways or upside-down pages in your documents. Rotate all pages or select specific ones.",
  keywords: ["rotate pdf", "pdf rotator", "rotate pdf pages", "turn pdf"],
  tags: ["pdf", "rotate", "edit", "document"],
  icon: "RotateCw",
  featured: false,
  popular: false,
  published: true,
  status: "published",
  categoryOrder: 6,
  toolOrder: 6,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["pdf-splitter", "pdf-page-extractor", "pdf-merger", "pdf-to-jpg"],
  searchPriority: 80,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["rotate pdf pages online", "turn pdf sideways", "fix pdf orientation", "pdf page rotation"],
  version: "1.0.0",
}