import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "HEIC to JPG Converter",
  slug: "heic-to-jpg",
  category: "image",
  shortDescription:
    "Convert HEIC/HEIF photos from iPhone to JPG format with adjustable quality and batch support.",
  longDescription:
    "Convert HEIC and HEIF images — the default photo format on iPhone and iPad — to universally compatible JPG format. Drag and drop your HEIC files, adjust output quality, preview the conversion, and download your JPGs instantly. Supports batch conversion of multiple files. All processing happens in your browser using the heic2any library — no uploads, no servers.",
  metaTitle:
    "HEIC to JPG Converter | Convert iPhone Photos to JPG Online Free | FreeKit",
  metaDescription:
    "Convert HEIC to JPG online for free. Turn iPhone photos into universally compatible JPG images. Batch convert, quality control, no upload needed — works in your browser.",
  keywords: [
    "heic to jpg",
    "heif to jpg",
    "heic converter",
    "iphone photos to jpg",
    "convert heic",
    "heic to jpeg",
    "apple heic to jpg",
    "heic image converter",
    "ios photo converter",
  ],
  tags: [
    "image",
    "converter",
    "heic",
    "heif",
    "jpg",
    "jpeg",
    "iphone",
    "apple",
    "ios",
    "photo",
  ],
  icon: "Smartphone",
  featured: true,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 5,
  toolOrder: 5,
  featuredOrder: 8,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-24",
  relatedTools: [
    "all-in-one-image-converter",
    "image-to-webp",
    "png-to-jpg",
    "image-compressor",
    "image-resizer",
  ],
  searchPriority: 91,
  readingTime: 3,
  clientSide: true,
  searchAliases: [
    "iphone photo converter",
    "heif to jpeg converter",
    "convert apple photos",
    "heic to jpg online free",
    "ios heic converter",
    "apple heic to jpeg",
  ],
  version: "1.0.0",
}
