import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Device Mockup Generator",
  slug: "device-mockup-generator",
  category: "creator",
  shortDescription: "Wrap your designs in realistic device mockup frames.",
  longDescription: "Present your web and app designs in beautiful device mockups including phones, tablets, laptops, and desktops. Upload any screenshot and wrap it in a realistic device frame. Perfect for portfolios, presentations, and marketing materials.",
  metaTitle: "Device Mockup Generator - Create Device Frames Free | FreeKit",
  metaDescription: "Generate device mockups for your designs for free. Wrap screenshots in phone, tablet, and laptop frames for presentations and portfolios.",
  keywords: ["device mockup", "mockup generator", "phone mockup", "screenshot frame"],
  tags: ["creator", "mockup", "design", "presentation"],
  icon: "Monitor",
  featured: false,
  popular: false,
  published: true,
  status: "published",
  categoryOrder: 6,
  toolOrder: 6,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["og-image-generator", "youtube-thumbnail-maker", "photo-collage-maker"],
  searchPriority: 76,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["phone mockup maker", "device frame generator", "screenshot mockup", "browser mockup"],
  version: "1.0.0",
}
