import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Link in Bio Generator",
  slug: "link-in-bio-generator",
  category: "creator",
  shortDescription: "Create a customizable link-in-bio page for your social profiles.",
  longDescription: "Build a beautiful, customizable link-in-bio page to share multiple links from a single URL. Perfect for Instagram, TikTok, Twitter, and other social platforms. Add your brand colors, custom buttons, and analytics tracking.",
  metaTitle: "Link in Bio Generator - Create Bio Link Pages Free | FreeKit",
  metaDescription: "Create a free link-in-bio page for your social media profiles. Share multiple links from one URL with custom branding and styling.",
  keywords: ["link in bio", "bio link", "link tree", "social links"],
  tags: ["creator", "social", "links", "marketing"],
  icon: "UserCircle",
  featured: false,
  popular: false,
  published: true,
  status: "published",
  categoryOrder: 4,
  toolOrder: 4,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["og-image-generator", "email-signature-generator", "qr-code-generator"],
  searchPriority: 75,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["bio link page", "link tree alternative", "social media links page", "multiple links one url"],
  version: "1.0.0",
}
