import type { ToolConfig } from "@/types"
export const toolConfig: ToolConfig = {
  title: "Webcam Test",
  slug: "webcam-test",
  category: "device",
  shortDescription: "Test your webcam online with live video preview, resolution info, mirror toggle, and screenshot capture.",
  longDescription: "A comprehensive webcam testing tool that uses the browser's getUserMedia API to access your camera. View a live video preview, see detailed resolution and frame rate information, toggle between mirrored and normal view, and capture screenshots directly from the video feed. All processing happens locally in your browser with no data uploaded to any server.",
  metaTitle: "Webcam Test - Test Your Camera Online Free | FreeKit",
  metaDescription: "Free online webcam test. Check if your camera works, see resolution info, mirror toggle, and take screenshots. No installation needed.",
  keywords: ["webcam test", "camera test", "test webcam online", "camera check", "webcam not working", "video test"],
  tags: ["camera", "webcam", "testing", "hardware"],
  icon: "Camera",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 4,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-23",
  updatedAt: "2025-07-23",
  relatedTools: ["microphone-test", "mirror-online", "touch-screen-test"],
  searchPriority: 91,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["camera check", "test camera", "is my webcam working", "webcam viewer"],
  version: "1.0.0",
}