import type { Metadata } from "next"
import { FileText } from "lucide-react"
import { siteConfig } from "@/config/site"
import { BreadcrumbNav } from "@/components/shared/breadcrumb-nav"

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `Terms and conditions for using ${siteConfig.name}. Please read these terms carefully before using our free online tools.`,
  alternates: { canonical: "/terms" },
}

const sections = [
  {
    title: "Acceptance of Terms",
    content: [
      `By accessing and using ${siteConfig.name} (${siteConfig.url}), you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.`,
      "These terms apply to all visitors, users, and others who access or use our tools and website.",
    ],
  },
  {
    title: "Description of Service",
    content: [
      `${siteConfig.name} provides free online tools for various purposes including but not limited to: SEO analysis, developer utilities, text processing, CSS design, general utilities, and calculators.`,
      "All tools are provided as-is for personal and commercial use. No registration or payment is required to use any tool.",
    ],
  },
  {
    title: "Use of Our Tools",
    content: [
      "You may use our tools for personal, educational, and commercial purposes.",
      "You agree not to: (a) use our tools for any unlawful purpose; (b) attempt to interfere with or disrupt the proper functioning of our website; (c) use automated systems (bots, scrapers) to access our services; (d) reproduce, duplicate, or copy any part of our website for commercial redistribution without written permission.",
      "Some tools generate output based on user input. You are responsible for the content you input and how you use the output.",
    ],
  },
  {
    title: "Intellectual Property",
    content: [
      `The ${siteConfig.name} website, including its design, code, text, graphics, and the overall look and feel, is owned by ${siteConfig.name} and protected by intellectual property laws.`,
      "The output generated by our tools belongs to you. You are free to use, modify, and distribute the results of our tools.",
      "You may not copy, modify, or redistribute the tool interfaces, underlying code, or website content without prior written permission.",
    ],
  },
  {
    title: "Disclaimer of Warranties",
    content: [
      `Our tools are provided "as is" and "as available" without warranties of any kind, either express or implied. ${siteConfig.name} does not guarantee that:`,
    ],
    list: [
      "The tools will be available at all times without interruption.",
      "The results produced by our tools will be error-free or accurate.",
      "The tools will meet your specific requirements or expectations.",
    ],
  },
  {
    title: "Limitation of Liability",
    content: [
      `To the fullest extent permitted by law, ${siteConfig.name} shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use our tools.`,
      "This includes, but is not limited to, damages for loss of data, revenue, or profits arising from the use of our tools.",
    ],
  },
  {
    title: "Data and Privacy",
    content: [
      "All tool processing happens in your browser. We do not collect, store, or transmit your input data to our servers. Please refer to our Privacy Policy for detailed information about data handling.",
    ],
  },
  {
    title: "Links to Third-Party Sites",
    content: [
      "Our website may contain links to third-party websites. We are not responsible for the content, privacy practices, or terms of service of any third-party websites.",
    ],
  },
  {
    title: "Changes to Terms",
    content: [
      "We reserve the right to modify these terms at any time. Changes will be posted on this page with an updated date. Your continued use of our services after changes constitutes acceptance of the new terms.",
    ],
  },
  {
    title: "Governing Law",
    content: [
      "These terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles.",
    ],
  },
  {
    title: "Contact",
    content: [
      `If you have questions about these Terms of Service, please contact us at ${siteConfig.email}.`,
    ],
  },
]

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
      <BreadcrumbNav
        items={[
          { label: "Home", href: "/" },
          { label: "Terms of Service" },
        ]}
      />

      <div className="mt-8 space-y-12">
        {/* Hero */}
        <div className="text-center">
          <div className="mx-auto mb-6 flex size-16 items-center justify-center rounded-2xl bg-primary/10">
            <FileText className="size-8 text-primary" />
          </div>
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Terms of Service
          </h1>
          <p className="mt-4 text-lg text-muted-foreground max-w-2xl mx-auto">
            Please read these terms carefully before using {siteConfig.name}.
          </p>
          <p className="mt-2 text-sm text-muted-foreground">
            Last updated: June 2025
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-8">
          {sections.map((section) => (
            <section key={section.title} className="space-y-3">
              <h2 className="text-xl font-semibold">{section.title}</h2>
              {section.content.map((paragraph, i) => (
                <p key={i} className="text-muted-foreground leading-relaxed">
                  {paragraph}
                </p>
              ))}
              {section.list && (
                <ul className="list-disc space-y-2 pl-6 text-muted-foreground">
                  {section.list.map((item, i) => (
                    <li key={i} className="leading-relaxed">{item}</li>
                  ))}
                </ul>
              )}
            </section>
          ))}
        </div>
      </div>
    </div>
  )
}