import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "PDF Merger",
  slug: "pdf-merger",
  category: "pdf",
  shortDescription: "Merge multiple PDF files into a single document quickly and easily.",
  longDescription: "Combine multiple PDF files into one seamless document. Upload two or more PDFs and merge them in your preferred order. Perfect for combining reports, invoices, or scanned pages into a single file.",
  metaTitle: "PDF Merger - Combine PDF Files Online Free | FreeKit",
  metaDescription: "Merge multiple PDF files into one document for free. Upload and combine PDFs in any order. No signup or watermarks.",
  keywords: ["merge pdf", "combine pdf", "pdf merger", "join pdf"],
  tags: ["pdf", "merge", "combine", "document"],
  icon: "Merge",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 1,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["pdf-splitter", "jpg-to-pdf", "pdf-to-jpg", "pdf-page-extractor"],
  searchPriority: 95,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["combine pdf files", "join pdfs together", "pdf combiner online", "merge documents"],
  version: "1.0.0",
}
