import type { FAQItem } from "@/types"

export const faqs: FAQItem[] = [
  {
    question: "What is PDF merging?",
    answer:
      "PDF merging is the process of combining two or more PDF files into a single document. The pages from each file are joined together in the order you specify, producing one cohesive PDF that contains all the content from the original files. This is useful when you need to compile reports, combine scanned pages, or consolidate multi-part documents.",
  },
  {
    question: "How does this PDF merger work?",
    answer:
      "Our PDF merger runs entirely in your browser using the pdf-lib library. You upload multiple PDF files, arrange them in your desired order using drag-and-drop or move buttons, and click the merge button. The tool creates a new PDF document and copies all pages from each uploaded file into it, then generates a downloadable merged PDF. No data is sent to any server.",
  },
  {
    question: "Is my data private when merging PDFs?",
    answer:
      "Absolutely. All PDF processing happens locally in your browser. Your files are never uploaded to any server, never stored, and never shared with third parties. Once you close the browser tab, all traces of your uploaded files are completely gone. This makes our tool safe for merging confidential documents like contracts, financial records, and personal files.",
  },
  {
    question: "Is there a file size or page count limit?",
    answer:
      "Since all processing happens in your browser, the practical limit depends on your device's available memory. Most modern computers and smartphones can comfortably handle merging dozens of PDFs with hundreds of pages each. There are no artificial file size restrictions imposed by our tool, so you can merge as many files as your device allows.",
  },
  {
    question: "What PDF formats are supported?",
    answer:
      "Our tool supports standard PDF files regardless of how they were created. Whether your PDFs were generated by Word, Excel, Google Docs, scanners, or any other application, they can be merged. The tool preserves all original content including text, images, fonts, hyperlinks, and form fields during the merge process.",
  },
  {
    question: "Can I change the order of pages before merging?",
    answer:
      "Yes, you have full control over the order of your files before merging. You can drag and drop files to reorder them using the grip handles, or use the move up and move down arrow buttons. The files will be merged in the exact order they appear in the list, with the first file's pages appearing first in the merged document.",
  },
  {
    question: "Is this PDF merger free to use?",
    answer:
      "Yes, this PDF merger is 100% free to use with no hidden costs, subscriptions, or premium tiers. There are no limits on how many PDFs you can merge or how often you can use the tool. No sign-up or account creation is required, and there are no watermarks added to your merged documents.",
  },
  {
    question: "Can I use this tool on my mobile phone?",
    answer:
      "Yes, our PDF merger is fully responsive and works on all modern mobile browsers including Safari on iOS and Chrome on Android. You can upload PDFs from your phone's storage, reorder them by tapping the move buttons, and download the merged file directly to your device. The interface adapts to smaller screens for easy touch interaction.",
  },
  {
    question: "Does merging affect the quality of my PDFs?",
    answer:
      "No, merging does not affect the quality of your PDFs in any way. The tool copies pages from the original files without recompressing or converting them. All text remains sharp, images retain their original resolution, and fonts are preserved exactly as they were. The merged output is a faithful combination of your original documents.",
  },
  {
    question: "Can I merge password-protected PDFs?",
    answer:
      "The tool can merge most standard PDF files. However, PDFs that are encrypted with password protection or have restrictive permissions may not be processable directly in the browser. If you encounter issues with protected files, you would need to remove the protection first using a dedicated PDF unlock tool before merging.",
  },
  {
    question: "How many PDF files can I merge at once?",
    answer:
      "There is no hard limit on the number of files you can merge. You can add as many PDFs as you need by dragging them onto the upload area or using the file picker. For very large batches of 50 or more files, processing time will depend on your device's capabilities, but the tool handles multi-file merging efficiently.",
  },
  {
    question: "What happens to my files after merging?",
    answer:
      "Nothing is stored after you complete the merge. Your uploaded files and the merged result exist only in your browser's memory during the session. Once you download the merged PDF and close the tab, all data is automatically cleared. We do not keep copies, create backups, or retain any information about your files.",
  },
]
