import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Duplicate Word Finder",
  slug: "duplicate-word-finder",
  category: "text-cleanup",
  shortDescription: "Find and highlight duplicate words in your text with frequency counts.",
  longDescription: "Quickly identify repeated words in your text. The Duplicate Word Finder shows a frequency list of all duplicate words, highlights them in the original text, and offers one-click removal of duplicates. Supports case-sensitive and case-insensitive modes.",
  metaTitle: "Free Duplicate Word Finder — Find Repeated Words Online | FreeKit",
  metaDescription: "Find duplicate words in your text online for free. See word frequency counts, highlight duplicates in context, and remove repeated words instantly in your browser.",
  keywords: ["duplicate word finder", "find repeated words", "word frequency", "duplicate words", "repeated words checker"],
  tags: ["text", "cleanup", "duplicates", "words", "frequency"],
  icon: "Copy",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 7,
  toolOrder: 7,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-02-20",
  updatedAt: "2025-06-05",
  relatedTools: ["remove-duplicate-lines", "word-counter", "remove-extra-spaces"],
  searchPriority: 75,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["find repeated words online", "word frequency counter", "check duplicate words", "highlight repeated words"],
  version: "1.0.0",
}
