import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Word Counter",
  slug: "word-counter",
  category: "text",
  shortDescription: "Count words, characters, sentences, and paragraphs instantly.",
  longDescription: "A comprehensive text analysis tool that counts words, characters (with and without spaces), sentences, paragraphs, and estimates reading time. Perfect for writers, students, and content creators who need precise text metrics.",
  metaTitle: "Free Word Counter Online | FreeKit",
  metaDescription: "Count words, characters, sentences, and paragraphs online for free. Get reading time estimates and detailed text analysis instantly.",
  keywords: ["word counter", "character counter", "text analysis", "word count"],
  tags: ["text", "counter", "words", "characters"],
  icon: "FileText",
  featured: true,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 1,
  featuredOrder: 3,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-01-08",
  updatedAt: "2025-06-22",
  relatedTools: [
    "case-converter",
    "lorem-ipsum-generator",
    "text-replacer",
    "remove-duplicate-lines",
    "keyword-density-checker",
  ],
  searchPriority: 96,
  readingTime: 4,
  clientSide: true,
  searchAliases: [
    "character counter",
    "letter counter",
    "text length",
    "word count tool",
  ],
  version: "1.0.0",
}
