import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "YouTube Thumbnail Maker",
  slug: "youtube-thumbnail-maker",
  category: "creator",
  shortDescription: "Design eye-catching YouTube thumbnails to boost video views.",
  longDescription: "Create attention-grabbing YouTube thumbnails that drive clicks and views. Choose from customizable templates with bold text, overlays, and effects. Optimize your thumbnail dimensions and design for maximum visibility in search results.",
  metaTitle: "YouTube Thumbnail Maker - Create Thumbnails Free | FreeKit",
  metaDescription: "Design YouTube thumbnails for free. Create attention-grabbing thumbnails with customizable templates, text overlays, and effects.",
  keywords: ["youtube thumbnail", "thumbnail maker", "video thumbnail", "yt thumbnail"],
  tags: ["creator", "youtube", "thumbnail", "design"],
  icon: "Youtube",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 5,
  toolOrder: 5,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["og-image-generator", "device-mockup-generator", "meme-generator", "photo-collage-maker"],
  searchPriority: 87,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["youtube thumbnail creator", "video thumbnail maker", "yt thumbnail design", "thumbnail generator"],
  version: "1.0.0",
}
