import type { Metadata } from "next"
import { ToolHeader } from "@/components/tool/tool-header"
import { ToolFooter } from "@/components/tool/tool-footer"
import { ToolPageCTA } from "@/components/tool/tool-page-cta"
import { FAQSection } from "@/components/shared/faq-section"
import { toolConfig } from "./config"
import { faqs } from "./faq"
import { getSchemas } from "./schema"
import { SqlFormatterTool } from "./tool"
import { generateToolMetadata } from "@/lib/tool-metadata"

export const metadata: Metadata = generateToolMetadata(toolConfig)

const LINK_CLASS = "font-medium text-primary underline underline-offset-4 hover:text-primary/80 transition-colors"

export default function SqlFormatterPage() {
  const schemas = getSchemas()
  return (
    <>
      {/* 1. JSON-LD Schemas */}
      {schemas.map((schema, i) => (
        <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
      ))}

      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8 md:py-12">
        {/* 2. Tool Header */}
        <ToolHeader tool={toolConfig} />

        {/* 3. Tool Component */}
        <section className="mt-8" aria-label="SQL Formatter">
          <SqlFormatterTool />
        </section>

        {/* 4. How to Use */}
        <section className="mt-16 space-y-4" aria-label="How to use">
          <h2 className="text-2xl font-bold tracking-tight">How to Use the SQL Formatter</h2>
          <ol className="list-decimal list-inside space-y-2 text-muted-foreground">
            <li><span className="text-foreground font-medium">Paste your SQL</span> — Enter or paste a SQL query into the input textarea. You can click "Load Sample" to try the tool with a complex example query containing JOINs, WHERE clauses, and GROUP BY.</li>
            <li><span className="text-foreground font-medium">Choose options</span> — Select 2-space or 4-space indentation, and toggle the "Uppercase Keywords" option to control whether SQL keywords are automatically uppercased in the output.</li>
            <li><span className="text-foreground font-medium">Format</span> — Click the "Format SQL" button or press Ctrl+Enter (Cmd+Enter on Mac). The formatted SQL appears in the output panel with proper structure and readability.</li>
            <li><span className="text-foreground font-medium">Copy or re-format</span> — Click "Copy SQL" to copy the formatted result. Use "Swap" to move the output back to input for re-formatting with different options. Click "Clear" to reset both panels.</li>
            <li><span className="text-foreground font-medium">Review stats</span> — The stats bar shows the keyword count and line count of the formatted output, helping you understand the complexity of your query.</li>
          </ol>
        </section>

        {/* 5. Features */}
        <section className="mt-16 space-y-4" aria-label="Features">
          <h2 className="text-2xl font-bold tracking-tight">Features</h2>
          <ul className="grid gap-2 sm:grid-cols-2 text-muted-foreground">
            {[
              "No external dependencies — pure JavaScript SQL parser and formatter built from scratch",
              "Supports all major SQL clauses: SELECT, FROM, WHERE, JOIN, GROUP BY, ORDER BY, HAVING, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP",
              "All JOIN variants: LEFT JOIN, RIGHT JOIN, INNER JOIN, FULL OUTER JOIN, CROSS JOIN",
              "CASE/WHEN/THEN/ELSE/END expression formatting with proper indentation",
              "Configurable indentation: 2 spaces or 4 spaces per level",
              "Uppercase keywords toggle — enforce SQL keyword casing conventions",
              "Preserves string literals and comments exactly as written",
              "Smart comma handling — newlines for column lists, inline for function arguments",
              "Keyboard shortcut: Ctrl+Enter / Cmd+Enter to format instantly",
              "Keyword and line count statistics for query complexity analysis",
              "Swap button to re-format with different settings",
              "100% client-side — no SQL is ever sent to a server",
            ].map((f) => (
              <li key={f} className="flex items-start gap-2">
                <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-primary" />
                {f}
              </li>
            ))}
          </ul>
        </section>

        {/* 6. Key Concepts */}
        <section className="mt-16 space-y-4" aria-label="Key concepts">
          <h2 className="text-2xl font-bold tracking-tight">Understanding SQL Formatting</h2>
          <div className="grid gap-4 sm:grid-cols-2">
            {[
              {
                t: "Why Format SQL?",
                d: "Formatted SQL is easier to read, debug, and maintain. In production environments, queries are often minified or generated by ORMs, making them hard to understand. A formatter adds structure that reveals the query's logic at a glance.",
              },
              {
                t: "Indentation Levels",
                d: "The formatter uses indentation to show the hierarchy of a SQL query. Main clauses (SELECT, FROM, WHERE) are at the base level. Conditions under WHERE are indented one level deeper. Subqueries would be indented further, creating a visual hierarchy that matches the logical structure.",
              },
              {
                t: "Keyword Casing Conventions",
                d: "Most SQL style guides recommend uppercase for keywords (SELECT, FROM, WHERE) and lowercase for identifiers (table names, column names). The uppercase toggle enforces this convention automatically, ensuring consistency across your codebase.",
              },
              {
                t: "SQL Dialect Compatibility",
                d: "The formatter handles standard SQL that works across MySQL, PostgreSQL, SQLite, SQL Server, and Oracle. Dialect-specific functions and syntax are preserved as-is since they are treated as identifiers by the parser.",
              },
            ].map((item) => (
              <div key={item.t} className="rounded-xl border border-border bg-card p-5 space-y-2">
                <h3 className="font-semibold">{item.t}</h3>
                <p className="text-sm text-muted-foreground">{item.d}</p>
              </div>
            ))}
          </div>
        </section>

        {/* 7. Use Cases */}
        <section className="mt-16 space-y-4" aria-label="Use cases">
          <h2 className="text-2xl font-bold tracking-tight">Common Use Cases</h2>
          <div className="grid gap-3 sm:grid-cols-2">
            {[
              { t: "Debugging ORM Queries", d: "ORMs like Prisma, Sequelize, or Hibernate often generate long, unformatted SQL. Paste the logged query into the formatter to understand what your ORM is actually executing." },
              { t: "Code Review", d: "Format SQL before submitting pull requests so reviewers can easily understand your queries. Consistently formatted SQL is a sign of professional code quality." },
              { t: "Documentation", d: "Add formatted SQL to technical documentation, wiki pages, or README files. Formatted queries are much easier for team members to read and understand." },
              { t: "Learning SQL", d: "If you are learning SQL, paste examples from tutorials or Stack Overflow into the formatter to see the proper structure with clear indentation and keyword placement." },
              { t: "Legacy Code Cleanup", d: "When inheriting a project with messy SQL queries, use the formatter to clean them up before refactoring. This makes the queries easier to understand and modify." },
              { t: "Query Optimization", d: "A well-formatted query makes it easier to spot optimization opportunities like missing indexes, unnecessary subqueries, or inefficient JOIN patterns." },
            ].map((item) => (
              <div key={item.t} className="rounded-lg border border-border bg-card p-4">
                <h3 className="text-sm font-semibold">{item.t}</h3>
                <p className="mt-1 text-sm text-muted-foreground">{item.d}</p>
              </div>
            ))}
          </div>
        </section>

        {/* 8. Tips */}
        <section className="mt-16 space-y-4" aria-label="Tips">
          <h2 className="text-2xl font-bold tracking-tight">SQL Formatting Tips</h2>
          <ul className="space-y-2 text-muted-foreground">
            {[
              { html: `Use Ctrl+Enter (or Cmd+Enter on Mac) as a keyboard shortcut to format SQL quickly without reaching for the mouse.` },
              { html: `After formatting, use the Swap button to re-format with different indentation settings. This is faster than re-pasting the query.` },
              { html: `Enable the uppercase keywords toggle to enforce a consistent SQL style across your team. Most style guides recommend uppercase keywords.` },
              { html: `The formatter preserves comments, so you can add documentation to your SQL before or after formatting without losing it.` },
              { html: `For very complex queries with subqueries, format incrementally — format the outer query first, then swap and format subqueries separately.` },
              { html: `After formatting SQL, use <a href="/tools/developer/json-formatter" class="${LINK_CLASS}">JSON Formatter</a> to format JSON data alongside your queries for consistent code documentation.` },
            ].map((tip, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-primary" />
                <span dangerouslySetInnerHTML={{ __html: tip.html }} />
              </li>
            ))}
          </ul>
        </section>

        {/* 9. FAQ Section */}
        <section className="mt-16" aria-label="FAQ">
          <FAQSection items={faqs} />
        </section>

        {/* 10. Related Tools + CTA */}
        <section className="mt-16" aria-label="Related tools">
          <ToolFooter tool={toolConfig} />
        </section>

        <ToolPageCTA />
      </div>
    </>
  )
}
