import type { FAQItem } from "@/types"

export const faqs: FAQItem[] = [
  { question: "What is a robots.txt file?", answer: "A robots.txt file is a plain text file placed at the root of your website (e.g., example.com/robots.txt) that tells search engine crawlers which pages or sections they are allowed or not allowed to crawl. It is the first file most crawlers look for when they visit your site." },
  { question: "Where should I put my robots.txt file?", answer: "The robots.txt file must be placed in the root directory of your website, accessible at yourdomain.com/robots.txt. It cannot be placed in a subdirectory. If your site is at example.com, the file must be at example.com/robots.txt." },
  { question: "What is a User-agent?", answer: "A User-agent identifies a specific search engine crawler. Common values include * (all crawlers), Googlebot (Google), Bingbot (Bing), Slurp (Yahoo), DuckDuckBot (DuckDuckGo), and facebookexternalhit (Facebook). Each User-agent section in robots.txt applies only to the specified crawler." },
  { question: "What does Disallow mean?", answer: "The Disallow directive specifies paths that a crawler should NOT access. 'Disallow: /admin/' prevents crawling of the /admin/ directory. 'Disallow: /' prevents crawling of the entire site. An empty Disallow (or no Disallow) means all pages are allowed." },
  { question: "What does Allow mean?", answer: "The Allow directive explicitly permits crawling of a path, even within a Disallowed directory. For example, Disallow: /admin/ followed by Allow: /admin/sitemap.xml allows the sitemap file while blocking the rest of the admin area. Allow is a Google extension but widely supported." },
  { question: "What is a Sitemap directive?", answer: "The Sitemap directive in robots.txt tells crawlers where to find your XML sitemap. Format: 'Sitemap: https://example.com/sitemap.xml'. You can include multiple Sitemap directives. This helps search engines discover and crawl your pages more efficiently." },
  { question: "What is Crawl-delay?", answer: "Crawl-delay specifies the number of seconds a crawler should wait between successive requests to your server. For example, 'Crawl-delay: 10' means 10 seconds between requests. Note: Googlebot does not support this directive — use Google Search Console's crawl rate setting instead." },
  { question: "Can robots.txt completely hide a page?", answer: "No. robots.txt is a suggestion, not a firewall. Well-behaved crawlers will respect it, but malicious bots or crawlers that don't check robots.txt can still access your pages. For sensitive content, use proper authentication and authorization. Never put confidential data in a Disallow path." },
  { question: "How do I test my robots.txt?", answer: "Google provides a robots.txt testing tool in Google Search Console that shows you how Googlebot interprets your file. You can also use online validators. After deploying, check that your important pages are being indexed and that disallowed pages are not appearing in search results." },
  { question: "Is this robots.txt generator free?", answer: "Yes, this tool is 100% free with no limits, no sign-up, and no hidden fees. All generation happens in your browser — no data is sent to any server." },
]
