import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Time Zone Converter",
  slug: "time-zone-converter",
  category: "calculator",
  shortDescription: "Convert times between different time zones around the world.",
  longDescription: "Convert time between any two time zones instantly. Supports all major world time zones with daylight saving time awareness. See multiple time zones simultaneously for scheduling meetings and calls.",
  metaTitle: "Free Time Zone Converter | FreeKit",
  metaDescription: "Convert time between time zones online for free. Supports all world time zones with daylight saving time. Schedule across regions easily.",
  keywords: [
    "time zone converter",
    "timezone converter",
    "world clock",
    "time conversion",
  ],
  tags: ["calculator", "timezone", "time", "conversion"],
  icon: "Globe",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 9,
  toolOrder: 9,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: [
    "days-between-dates",
    "timestamp-converter",
    "unit-converter",
    "percentage-calculator",
  ],
  searchPriority: 84,
  readingTime: 4,
  clientSide: true,
  searchAliases: [
    "timezone converter online",
    "world time converter",
    "time difference calculator",
    "convert time zone",
  ],
  version: "1.0.0",
}
