import type { ToolConfig } from "@/types"
export const toolConfig: ToolConfig = {
  title: "UUID Generator",
  slug: "uuid-generator",
  category: "developer",
  shortDescription: "Generate random UUIDs (v4) instantly.",
  longDescription: "Generate cryptographically random UUIDs (version 4) for use in databases, APIs, and distributed systems. Generate single or bulk UUIDs with options for uppercase, lowercase, and no-hyphen formats.",
  metaTitle: "Free UUID Generator | FreeKit",
  metaDescription: "Generate random UUIDs (v4) online for free. Create single or bulk UUIDs instantly with format options.",
  keywords: ["uuid generator", "guid generator", "uuid v4", "random id"],
  tags: ["uuid", "generator", "developer", "id"],
  icon: "Hash",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 3,
  toolOrder: 3,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-01-14",
  updatedAt: "2025-06-18",
  relatedTools: ["password-generator", "hash-generator", "base64-encoder", "json-formatter"],
  searchPriority: 82,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["guid generator", "unique id generator", "uuid creator"],
  version: "1.0.0",
}
