import type { FAQItem } from "@/types"

export const faqs: FAQItem[] = [
  {
    question: "What is a UUID and why should I use one?",
    answer: "A UUID (Universally Unique Identifier) is a 128-bit identifier that is practically guaranteed to be unique across space and time. It is represented as a 36-character string in the format 8-4-4-4-12 (e.g., 550e8400-e29b-41d4-a716-446655440000). UUIDs are ideal for primary keys in databases, distributed system identifiers, and any scenario where you need a unique ID without coordination between systems.",
  },
  {
    question: "What is the difference between UUID v1, v3, v4, and v5?",
    answer: "UUID v1 is time-based and combines a timestamp with the machine's MAC address, making it time-sortable but potentially exposing hardware identity. UUID v3 and v5 are namespace-based — they generate deterministic UUIDs from a name and namespace using MD5 (v3) or SHA-1 (v5) hashing, so the same input always produces the same UUID. UUID v4 is entirely random, using 122 cryptographically random bits. For most applications, v4 is recommended because it offers the best balance of simplicity, uniqueness, and privacy.",
  },
  {
    question: "Is a GUID the same as a UUID?",
    answer: "GUID (Globally Unique Identifier) is Microsoft's implementation of the UUID standard. The terms are often used interchangeably, and both refer to the same 128-bit identifier format. The main difference is cultural — GUID is more commonly used in the Microsoft/.NET ecosystem, while UUID is the standard term used in RFC 4122 and most other platforms. Our tool generates standard RFC 4122 UUIDs that are fully compatible with GUID usage.",
  },
  {
    question: "How unique is a UUID v4 really?",
    answer: "UUID v4 uses 122 random bits (6 bits are reserved for version and variant fields), giving approximately 5.3 × 10³⁶ possible values. The probability of generating a duplicate UUID v4 in isolation is astronomically low — you would need to generate approximately 2.71 quintillion (2.71 × 10¹⁸) UUIDs before having a 50% chance of any collision. For practical purposes in databases and applications, UUID v4 collisions are effectively impossible.",
  },
  {
    question: "Can UUIDs be used as database primary keys?",
    answer: "Yes, UUIDs are commonly used as primary keys, especially in distributed systems where centralized ID generation is impractical. However, there are trade-offs: UUIDs are 4× larger than 32-bit integers and their randomness can cause index fragmentation in B-tree databases like MySQL/PostgreSQL, leading to slower inserts. For high-write workloads, consider using UUID v7 (time-ordered) or a combination of timestamp + random suffix to maintain sortability while keeping uniqueness.",
  },
  {
    question: "Is crypto.randomUUID() secure enough for production use?",
    answer: "Yes, crypto.randomUUID() uses the Web Crypto API's cryptographically secure random number generator (CSPRNG), which is suitable for security-sensitive applications. Unlike Math.random(), which is not cryptographically secure and can be predicted, the CSPRNG draws from the operating system's entropy pool (e.g., /dev/urandom on Linux, CryptGenRandom on Windows). This makes UUID v4 generated by crypto.randomUUID() safe for use in access tokens, session identifiers, and any context where predictability would be a security risk.",
  },
  {
    question: "What does the no-hyphen format look like and when should I use it?",
    answer: "A standard UUID is 550e8400-e29b-41d4-a716-446655440000 (36 characters with hyphens). The no-hyphen format removes all dashes: 550e8400e29b41d4a716446655440000 (32 characters). Use the no-hyphen format when storing UUIDs in systems with tight storage constraints, using them in URLs, passing them as hex values to APIs that expect raw hex, or embedding them in filenames and file paths where hyphens may cause issues.",
  },
  {
    question: "How many UUIDs can I generate at once?",
    answer: "Our UUID Generator supports generating 1 to 100 UUIDs in a single batch. This is useful when you need to pre-generate IDs for testing, seed a database with sample data, or create multiple identifiers at once. All generation happens entirely in your browser using crypto.randomUUID(), so there are no server limits — the batch size cap is set to ensure the page remains responsive and readable.",
  },
  {
    question: "Are there any browser compatibility issues with crypto.randomUUID()?",
    answer: "crypto.randomUUID() is supported in all modern browsers: Chrome 92+, Firefox 95+, Safari 15.4+, Edge 92+, and all mobile browsers based on these engines. It is not available in Internet Explorer (which is no longer supported by Microsoft) or very old browser versions. For environments where the Web Crypto API is unavailable, a polyfill using crypto.getRandomValues() can generate RFC 4122-compliant UUID v4 identifiers.",
  },
  {
    question: "What are common use cases for UUIDs in software development?",
    answer: "UUIDs are used extensively across software: as primary keys in distributed databases (DynamoDB, CouchDB, Firebase), for request/correlation tracing in microservices, as session tokens and CSRF tokens in web applications, for naming uploaded files to avoid conflicts, as message IDs in message queues (Kafka, RabbitMQ), for API resource identifiers in REST and GraphQL, as installation IDs and device fingerprints, and for cache key generation in caching layers.",
  },
]
