import type { ToolConfig } from "@/types"
export const toolConfig: ToolConfig = {
  title: "Water Eject Tool",
  slug: "water-eject-tool",
  category: "device",
  shortDescription: "Eject water from your device speakers using low-frequency sound waves through the Web Audio API.",
  longDescription: "A web-based water ejection tool that plays a carefully designed low-frequency sine wave sweep (80-400Hz) to vibrate water out of your device's speakers. Similar to the Apple Watch water eject feature, this tool uses the Web Audio API OscillatorNode to generate sound waves that help push trapped water out of your phone, laptop, or tablet speakers. The 30-second sweep covers the optimal frequency range for maximum water displacement.",
  metaTitle: "Water Eject Tool - Remove Water from Speakers | FreeKit",
  metaDescription: "Free online water eject tool. Play low-frequency sound waves to safely remove water trapped in your device speakers. Works on phones, laptops, and tablets.",
  keywords: ["water eject", "water in speakers", "speaker water removal", "eject water", "water damage", "phone water eject", "laptop speakers wet"],
  tags: ["audio", "speakers", "maintenance", "device-care"],
  icon: "Droplets",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 1,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-23",
  updatedAt: "2025-07-23",
  relatedTools: ["speaker-test", "noise-level-meter", "webcam-test"],
  searchPriority: 90,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["water removal", "speaker cleaner", "eject water sound", "water out of phone"],
  version: "1.0.0",
}