import type { FAQItem } from "@/types"
export const faqs: FAQItem[] = [
  { question: "How does the water eject tool work?", answer: "The tool generates low-frequency sine waves (80-400Hz) through your device speakers using the Web Audio API. These sound waves create vibrations that help push trapped water out of the speaker grills, similar to how the Apple Watch water eject feature works." },
  { question: "Is it safe to use on my phone?", answer: "Yes, this tool is safe for most devices. It only plays audio through your speakers and does not interact with any hardware directly. However, if your device is already showing signs of significant water damage, consult a professional repair service." },
  { question: "How long should I run the water eject?", answer: "The default sweep runs for 30 seconds, which is typically sufficient. You can run it multiple times if needed. Place your device speaker-down on a soft cloth to help water drain out." },
  { question: "Why does it use low-frequency sounds?", answer: "Low-frequency sound waves (80-400Hz) create larger physical vibrations in the speaker cone compared to higher frequencies. These larger vibrations are more effective at displacing water droplets trapped near the speaker mesh." },
  { question: "Does this work on laptops and tablets too?", answer: "Yes, this tool works on any device with speakers that can play audio from a web browser, including laptops, tablets, and smartphones. The effectiveness may vary depending on speaker size and water amount." },
  { question: "What should I do before using this tool?", answer: "Wipe off any visible water on the outside of your device, hold it with the speaker facing downward, and ensure the volume is turned up to maximum. Place a towel or cloth underneath to absorb the ejected water." },
  { question: "Will this fix water-damaged speakers permanently?", answer: "This tool helps remove water that is physically trapped in the speaker area. If there is corrosion or electrical damage from prolonged water exposure, professional repair may be needed. This tool is for immediate water ejection, not long-term damage repair." },
  { question: "Can I use this tool without internet?", answer: "No, you need an internet connection to load the webpage. However, once loaded, the audio generation happens entirely in your browser using the Web Audio API, so it does not stream any audio from a server." },
  { question: "Why might the water eject not work?", answer: "If the water has been sitting for a long time, it may have caused mineral deposits or corrosion. Also, if your device's speakers are already damaged, they may not produce strong enough vibrations. In such cases, professional cleaning is recommended." },
  { question: "What is the optimal volume level?", answer: "Set your device volume to maximum (100%) for the best results. The stronger the sound waves, the more effective the water ejection will be." },
]