import type { FAQItem } from "@/types"

export const faqs: FAQItem[] = [
  { question: "What is keyword density?", answer: "Keyword density is the percentage of times a keyword or phrase appears in a text compared to the total number of words. For example, if your keyword appears 5 times in a 500-word article, the density is 1%. It's one of many factors search engines consider when determining a page's relevance for a particular keyword." },
  { question: "What is the ideal keyword density for SEO?", answer: "Most SEO experts recommend a primary keyword density of 1-2% for optimal results. Going above 3% risks being flagged as keyword stuffing by search engines, which can actually hurt your rankings. The key is natural-sounding content that includes your keyword where it makes sense, not forced repetition." },
  { question: "What is keyword stuffing?", answer: "Keyword stuffing is the practice of overloading a webpage with keywords in an attempt to manipulate search rankings. This includes unnaturally repeating keywords, hiding text, or adding irrelevant keywords. Search engines penalize keyword stuffing, and it creates a poor user experience. Focus on natural, helpful content instead." },
  { question: "Should I check single words or phrases?", answer: "Both are valuable. Single-word density (e.g., 'SEO') shows broad topic focus, while phrase density (e.g., 'keyword density checker') shows specific long-tail keyword targeting. Our tool analyzes both — enter a single word for one-word analysis, or a multi-word phrase for phrase density analysis." },
  { question: "Does keyword density still matter in 2025?", answer: "Keyword density is less important than it was years ago, but it still serves as a useful guideline. Modern search engines use semantic understanding (like Google's BERT and MUM) to understand content context. However, ensuring your target keyword appears naturally a few times still signals topical relevance." },
  { question: "How is word count calculated?", answer: "Our tool counts words by splitting the text on whitespace and filtering out empty strings. It counts total words, unique words (case-insensitive deduplication), sentences (split by period, exclamation, and question mark), and paragraphs (split by double newlines). Punctuation is not counted as words." },
  { question: "What are stop words?", answer: "Stop words are common words like 'the', 'is', 'at', 'which', 'on' that search engines typically ignore. They make up about 40-50% of most English text. Our tool counts all words including stop words in the total, as this is the standard method for calculating keyword density." },
  { question: "How do I use this tool for SEO optimization?", answer: "Paste your content, enter your target keyword, and check the density. Aim for 1-2% for your primary keyword. Also review the top words table to discover secondary keywords you may want to target. Check that your content reads naturally and that keywords are distributed throughout, not clustered in one section." },
  { question: "Can I analyze a webpage URL directly?", answer: "Currently, this tool analyzes text that you paste directly. To analyze a webpage, copy the text content from the page and paste it here. For direct URL analysis, you would need a server-side tool that fetches and parses the page HTML." },
  { question: "Is this keyword density checker free?", answer: "Yes, this tool is 100% free with no limits, no sign-up, and no hidden fees. All analysis happens in your browser — your content is never sent to any server." },
]
