import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Hash Generator",
  slug: "hash-generator",
  category: "developer",
  shortDescription: "Generate MD5, SHA-1, SHA-256, and other hash values from text.",
  longDescription: "Generate cryptographic hash values using multiple algorithms including MD5, SHA-1, SHA-256, and SHA-512. Perfect for verifying file integrity, creating checksums, and password hashing demonstrations.",
  metaTitle: "Free Hash Generator Online | FreeKit",
  metaDescription: "Generate MD5, SHA-1, SHA-256, and SHA-512 hashes online for free. Compute cryptographic hashes instantly in your browser.",
  keywords: ["hash generator", "sha256", "md5", "sha1", "checksum"],
  tags: ["hash", "security", "sha", "crypto"],
  icon: "Lock",
  featured: true,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 9,
  toolOrder: 9,
  featuredOrder: 15,
  difficulty: "Intermediate",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["base64-encoder", "password-generator", "jwt-decoder", "json-validator"],
  searchPriority: 86,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["sha256 generator", "md5 hash", "checksum calculator", "sha generator"],
  version: "1.0.0",
}
