import type { ToolConfig } from "@/types"
export const toolConfig: ToolConfig = {
  title: "Internet Speed Test",
  slug: "internet-speed-test",
  category: "device",
  shortDescription: "Measure your download speed by fetching a test file. See real-time progress and results in Mbps.",
  longDescription: "A simple internet speed test that measures your download speed by fetching known-size data chunks from a CDN and calculating throughput in real-time. Unlike complex speed tests that require multiple servers, this tool provides a quick and straightforward download speed estimate using a reliable public test file. Results are displayed with a progress bar and detailed speed metrics.",
  metaTitle: "Internet Speed Test - Check Download Speed Online | FreeKit",
  metaDescription: "Free internet speed test. Check your download speed in Mbps with real-time progress. Quick and simple speed measurement.",
  keywords: ["internet speed test", "download speed test", "speed test online", "check internet speed", "bandwidth test", "network speed"],
  tags: ["network", "speed", "testing", "internet"],
  icon: "Gauge",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 8,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-23",
  updatedAt: "2025-07-23",
  relatedTools: ["noise-level-meter", "microphone-test", "speaker-test"],
  searchPriority: 93,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["download speed", "bandwidth check", "check my speed", "internet speed"],
  version: "1.0.0",
}