import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Character Counter",
  slug: "character-counter",
  category: "text",
  shortDescription: "Count characters, words, and sentences with real-time analysis.",
  longDescription: "A precise character counting tool that tracks character count (with and without spaces), word count, sentence count, paragraph count, and byte size. Ideal for Twitter posts, SMS messages, meta descriptions, and any content with character limits.",
  metaTitle: "Free Character Counter Online | FreeKit",
  metaDescription: "Count characters, words, and sentences online for free. Real-time text analysis with character limits for social media, SEO, and more.",
  keywords: ["character counter", "letter counter", "char count", "text length checker"],
  tags: ["text", "counter", "characters", "limits"],
  icon: "ALargeSmall",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 2,
  toolOrder: 2,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-01-08",
  updatedAt: "2025-07-22",
  relatedTools: ["word-counter", "case-converter", "text-sorter", "lorem-ipsum-generator"],
  searchPriority: 88,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["letter counter", "char count tool", "text length counter", "character limit checker"],
  version: "1.0.0",
}
