import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Invoice Generator",
  slug: "invoice-generator",
  category: "business",
  shortDescription: "Create professional invoices with line items, tax, and discounts.",
  longDescription: "Generate clean, professional invoices for your business in seconds. Add your business info, client details, line items with automatic calculations, tax rates, discounts, and notes. Preview your invoice live and print or download it directly.",
  metaTitle: "Invoice Generator - Create Professional Invoices Free | FreeKit",
  metaDescription: "Create professional invoices for free with automatic calculations. Add line items, tax, discounts, and print or download your invoice instantly.",
  keywords: ["invoice generator", "free invoice", "invoice maker", "create invoice", "online invoice"],
  tags: ["business", "invoice", "billing", "finance", "documents"],
  icon: "Receipt",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 2,
  featuredOrder: 0,
  difficulty: "Intermediate",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["resume-builder", "quote-generator", "timesheet-calculator", "payslip-generator"],
  searchPriority: 92,
  readingTime: 6,
  clientSide: true,
  searchAliases: ["invoice creator", "billing tool", "free invoice maker", "make an invoice", "invoice template"],
  version: "1.0.0",
}
