import type { ToolConfig } from "@/types"
export const toolConfig: ToolConfig = {
  title: "Dead Pixel Test",
  slug: "dead-pixel-test",
  category: "device",
  shortDescription: "Detect dead or stuck pixels on your screen with fullscreen solid color displays.",
  longDescription: "A dead pixel testing tool that displays fullscreen solid colors (red, green, blue, white, and black) to help you identify dead, stuck, or hot pixels on your screen. Dead pixels appear as black dots on colored backgrounds, while stuck pixels show as colored dots on all backgrounds. Simply click or press spacebar to cycle through colors and press ESC to exit fullscreen.",
  metaTitle: "Dead Pixel Test - Find Stuck & Dead Pixels | FreeKit",
  metaDescription: "Free dead pixel test. Display fullscreen colors to find dead, stuck, or hot pixels on any screen. Click to cycle colors. No download needed.",
  keywords: ["dead pixel test", "stuck pixel", "dead pixel", "pixel test", "screen test", "find dead pixels", "pixel checker"],
  tags: ["display", "screen", "testing", "hardware"],
  icon: "Monitor",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 6,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-23",
  updatedAt: "2025-07-23",
  relatedTools: ["touch-screen-test", "webcam-test", "speaker-test"],
  searchPriority: 87,
  readingTime: 2,
  clientSide: true,
  searchAliases: ["stuck pixel test", "screen pixel check", "find bad pixels", "pixel fixer"],
  version: "1.0.0",
}