import type { FAQItem } from "@/types"
export const faqs: FAQItem[] = [
  { question: "What is a dead pixel?", answer: "A dead pixel is a pixel on your screen that is permanently off (always black), regardless of what color should be displayed. It is caused by a manufacturing defect or physical damage to the pixel's transistor." },
  { question: "What is a stuck pixel?", answer: "A stuck pixel is a pixel that is always on and displays one specific color (red, green, or blue) regardless of what should be shown. Unlike dead pixels, stuck pixels may sometimes be fixed with software or gentle pressure." },
  { question: "How do I use this test?", answer: "Click 'Start Test' to enter fullscreen mode. Click anywhere or press Space to cycle through colors (red, green, blue, white, black). Carefully inspect the screen for any dots that don't match the background color. Press ESC to exit." },
  { question: "Which colors should I check?", answer: "Check all five colors: Red, Green, and Blue will reveal stuck pixels of those specific colors. White will show any dark/dead pixels. Black will reveal stuck or hot pixels as bright colored dots." },
  { question: "Can dead pixels be fixed?", answer: "Dead pixels (permanently off) usually cannot be fixed and require hardware replacement. Stuck pixels (stuck on one color) may sometimes be fixed by running pixel-fixing software that rapidly cycles colors, or by gently massaging the area with a soft cloth." },
  { question: "How many dead pixels are acceptable?", answer: "Industry standards (ISO 9241) generally allow a small number of defective pixels depending on screen size and class. Class I displays should have zero defective pixels, while Class II allows some. Check your manufacturer's warranty terms." },
  { question: "Why does the test need fullscreen?", answer: "Fullscreen mode eliminates browser UI, taskbars, and other screen elements that could interfere with pixel inspection. A solid, uniform color across the entire screen makes it much easier to spot defective pixels." },
  { question: "Does this work on mobile screens?", answer: "Yes! This test works on any device with a screen. On mobile devices, tap the screen to cycle colors. Use landscape orientation for the most uniform color display." },
  { question: "What if I find a dead pixel?", answer: "If your device is under warranty, contact the manufacturer for a repair or replacement. If it's out of warranty, stuck pixel fixer tools or videos may help with stuck (not dead) pixels." },
  { question: "Is this test accurate?", answer: "This test is a reliable visual inspection method. Displaying pure colors at fullscreen gives you the best chance of spotting any pixel anomalies. For professional calibration, consider dedicated hardware testing tools." },
]