import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Meme Generator",
  slug: "meme-generator",
  category: "creator",
  shortDescription: "Create funny memes with custom text and popular templates.",
  longDescription: "Generate memes instantly using popular templates or your own images. Add custom top and bottom text with various font styles and sizes. Share your creations directly to social media or download them for later use.",
  metaTitle: "Meme Generator - Create Memes Online Free | FreeKit",
  metaDescription: "Create memes online for free. Choose from popular templates or upload your own images. Add custom text and share instantly.",
  keywords: ["meme generator", "meme maker", "create meme", "funny meme"],
  tags: ["creator", "meme", "fun", "social"],
  icon: "SmilePlus",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 7,
  toolOrder: 7,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["youtube-thumbnail-maker", "og-image-generator", "photo-collage-maker", "image-cropper"],
  searchPriority: 89,
  readingTime: 4,
  clientSide: true,
  searchAliases: ["meme maker online", "meme creator", "funny image generator", "meme template maker"],
  version: "1.0.0",
}