import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Line Break Remover",
  slug: "line-break-remover",
  category: "text-cleanup",
  shortDescription: "Remove or convert line breaks in text instantly.",
  longDescription: "Easily remove all line breaks, convert them to spaces, or transform text into comma-separated values. A free browser-based tool for quick text formatting and line break cleanup.",
  metaTitle: "Free Line Break Remover Tool — Remove or Convert Line Breaks | FreeKit",
  metaDescription: "Remove line breaks from text online for free. Convert line breaks to spaces, comma-separated values, or remove them entirely. Fast, private, browser-based tool.",
  keywords: ["remove line breaks", "line break remover", "convert line breaks", "remove newlines", "text formatting"],
  tags: ["text", "cleanup", "line breaks", "formatting"],
  icon: "WrapText",
  featured: false,
  popular: false,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 2,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-02-20",
  updatedAt: "2025-06-05",
  relatedTools: ["remove-extra-spaces", "text-replacer", "remove-duplicate-lines"],
  searchPriority: 82,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["remove newlines", "convert newlines to spaces", "join lines", "unwrap text"],
  version: "1.0.0",
}
