import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "List Cleaner",
  slug: "list-cleaner",
  category: "text-cleanup",
  shortDescription: "Clean, deduplicate, sort, and reformat lists with one click.",
  longDescription: "Transform messy lists into clean, organized data. Remove empty lines, duplicates, numbering, bullet points; trim whitespace; sort alphabetically; and add new numbering or bullet formatting. A fast, free, browser-based list cleanup tool.",
  metaTitle: "Free List Cleaner Tool — Clean, Sort & Deduplicate Lists Online | FreeKit",
  metaDescription: "Clean up lists online for free. Remove duplicates, empty lines, numbering, bullet points, sort A-Z or Z-A, trim whitespace, and reformat your list instantly in your browser.",
  keywords: ["list cleaner", "clean list", "remove duplicates from list", "sort list online", "remove numbering", "list formatter"],
  tags: ["text", "cleanup", "list", "deduplicate", "sort"],
  icon: "ListOrdered",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 6,
  toolOrder: 6,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-02-20",
  updatedAt: "2025-06-05",
  relatedTools: ["remove-duplicate-lines", "remove-extra-spaces", "text-sorter"],
  searchPriority: 78,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["clean list online", "remove list duplicates", "sort list alphabetically", "remove bullet points", "list formatter"],
  version: "1.0.0",
}
