import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "Remove Extra Spaces",
  slug: "remove-extra-spaces",
  category: "text-cleanup",
  shortDescription: "Remove extra spaces, tabs, and blank lines from text instantly.",
  longDescription: "Clean up messy text by removing extra spaces, leading/trailing whitespace, tabs, blank lines, and normalizing line breaks. A fast, free, browser-based text cleanup tool.",
  metaTitle: "Free Remove Extra Spaces Tool — Clean Up Text Online | FreeKit",
  metaDescription: "Remove extra spaces, tabs, and blank lines from your text online for free. Normalize whitespace, trim lines, and clean up formatting instantly in your browser.",
  keywords: ["remove extra spaces", "clean text", "remove blank lines", "normalize whitespace", "text cleanup"],
  tags: ["text", "cleanup", "spaces", "whitespace"],
  icon: "Space",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 1,
  toolOrder: 1,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-02-20",
  updatedAt: "2025-06-05",
  relatedTools: ["line-break-remover", "text-replacer", "remove-duplicate-lines", "case-converter"],
  searchPriority: 88,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["clean text spaces", "remove whitespace", "normalize text", "trim spaces online"],
  version: "1.0.0",
}
