import type { ToolConfig } from "@/types"

export const toolConfig: ToolConfig = {
  title: "ZIP Extract",
  slug: "zip-extract",
  category: "document",
  shortDescription: "Extract and preview files from ZIP archives instantly.",
  longDescription: "Upload a ZIP file and instantly browse its contents with a full file tree view. Preview text files and images directly in your browser, download individual files or extract all at once. No server upload required — everything runs locally for maximum privacy and speed.",
  metaTitle: "ZIP Extractor - Extract ZIP Files Online Free | FreeKit",
  metaDescription: "Extract ZIP files online for free. Browse file contents, preview text and images, and download individual files. 100% client-side — your files never leave your browser.",
  keywords: ["zip extractor", "extract zip online", "unzip files", "zip file viewer", "open zip file"],
  tags: ["document", "zip", "extract", "archive"],
  icon: "FolderOpen",
  featured: false,
  popular: true,
  published: true,
  status: "published",
  categoryOrder: 3,
  toolOrder: 3,
  featuredOrder: 0,
  difficulty: "Beginner",
  author: "FreeKit Team",
  createdAt: "2025-07-22",
  updatedAt: "2025-07-22",
  relatedTools: ["pdf-to-text", "jpg-to-pdf", "image-compressor", "pdf-merger"],
  searchPriority: 86,
  readingTime: 3,
  clientSide: true,
  searchAliases: ["unzip file online", "open zip archive", "extract zip contents", "view zip files"],
  version: "1.0.0",
}
