import type { FAQItem } from "@/types"

export const faqs: FAQItem[] = [
  {
    question: "What is a file checksum?",
    answer:
      "A file checksum is a fixed-length string generated by running a cryptographic hash algorithm on a file's contents. Even a tiny change in the file (a single byte) produces a completely different checksum. This makes checksums ideal for verifying that a file has not been corrupted or tampered with.",
  },
  {
    question: "What hash algorithms are supported?",
    answer:
      "This tool calculates four common hash algorithms: MD5 (128-bit), SHA-1 (160-bit), SHA-256 (256-bit), and SHA-512 (512-bit). SHA-256 is the most commonly used for file verification today. MD5 and SHA-1 are included for legacy compatibility but are considered cryptographically weak.",
  },
  {
    question: "How do I verify a file's integrity?",
    answer:
      "First, calculate the checksum of your file using this tool. Then, compare it against a known-good checksum provided by the file's source (e.g., a software download page). If the hashes match exactly, the file is intact. If they differ, the file was corrupted during download or has been tampered with.",
  },
  {
    question: "Is my file uploaded to a server?",
    answer:
      "No. The file is read into your browser's memory and all hash calculations are performed using the Web Crypto API. The file never leaves your device. Once you navigate away or close the tab, the file data is released from memory.",
  },
  {
    question: "Why are there multiple hash algorithms?",
    answer:
      "Different contexts use different algorithms. MD5 is common for legacy systems and quick integrity checks. SHA-1 was widely used but has known collision vulnerabilities. SHA-256 is the current standard for most security applications. SHA-512 provides even more bits of security and is used in high-assurance environments.",
  },
  {
    question: "What is the difference between MD5 and SHA-256?",
    answer:
      "MD5 produces a 32-character hex string and is fast but has known collision attacks. SHA-256 produces a 64-character hex string and is currently considered secure against collision attacks. For security-critical verification, always use SHA-256 or SHA-512. MD5 is fine for non-security checksums like detecting accidental file corruption.",
  },
  {
    question: "Can this tool compare two files?",
    answer:
      "Not directly, but you can calculate the hash of each file separately and visually compare the hashes. If both hashes are identical, the files are the same. For a more efficient approach, compare just the file sizes first — if they differ, the files are definitely different.",
  },
  {
    question: "Is there a file size limit?",
    answer:
      "Since the file is loaded into browser memory, very large files (over 500 MB) may cause issues depending on your device's available RAM. For typical files (documents, images, executables, compressed archives), the tool works perfectly.",
  },
  {
    question: "Why might my checksum differ from the expected value?",
    answer:
      "Several reasons: the file was corrupted during download or transfer, the file was modified after the checksum was generated, you are using a different algorithm than expected, line ending differences (CRLF vs LF) for text files, or extra whitespace in the expected hash value. Always verify you are comparing the same algorithm.",
  },
  {
    question: "How does the verification feature work?",
    answer:
      "Paste a known hash value in the verification field, and the tool compares it against all four calculated hashes. If it matches any of them, it shows a green confirmation with the matching algorithm name. If it does not match any, it shows a red mismatch indicator.",
  },
]
